In [168]:
import torch

In [169]:
f = torch.nn.Sequential(
    torch.nn.Linear(1,5),
)

g = torch.nn.Sequential(
    torch.nn.Linear(1,5),
)

h = torch.nn.Sequential(
    torch.nn.Linear(1,5),
)

x = torch.tensor([0.0])

In [170]:
yf = f(x)

In [171]:
yg = g(x)

In [172]:
for i,(pf,pg,ph) in enumerate(zip(f.parameters(), g.parameters(), h.parameters()), start=1):
    with torch.no_grad():
        ph[:] = .5*pf + .5*pg

In [173]:
yh = h(x)
yf, yg, yh

(tensor([ 0.4078, -0.4967,  0.2647,  0.3822,  0.0470], grad_fn=<AddBackward0>),
 tensor([ 0.9509, -0.9288, -0.7978, -0.1891,  0.0025], grad_fn=<AddBackward0>),
 tensor([ 0.6793, -0.7127, -0.2666,  0.0966,  0.0248], grad_fn=<AddBackward0>))